return {
	"folke/trouble.nvim",
	cmd = "Trouble",
	keys = {
		{ "<leader>xx", "<cmd>Trouble diagnostics toggle focus=true<cr>", desc = "Diagnostics (Trouble)" },
		{ "<leader>xX", "<cmd>Trouble diagnostics toggle filter.buf=0 focus=true<cr>", desc = "Buffer Diagnostics" },
		{ "<leader>xs", "<cmd>Trouble symbols toggle focus=true<cr>", desc = "Symbols (Trouble)" },
		{ "<leader>xl", "<cmd>Trouble lsp toggle focus=true<cr>", desc = "LSP Definitions/References" },
		{ "<leader>xq", "<cmd>Trouble qflist toggle focus=true<cr>", desc = "Quickfix List" },
		{ "<leader>xL", "<cmd>Trouble loclist toggle focus=true<cr>", desc = "Location List" },
		{ "[q", function() require("trouble").prev({ skip_groups = true, jump = true }) end, desc = "Prev Trouble Item" },
		{ "]q", function() require("trouble").next({ skip_groups = true, jump = true }) end, desc = "Next Trouble Item" },
	},
	opts = {
		auto_close = true,
		auto_preview = true,
		auto_refresh = true,
		focus = true,
		follow = true,
		indent_guides = true,
		multiline = true,
		pinned = false,
		warn_no_results = true,
		open_no_results = false,
		win = {
			type = "split",
			position = "bottom",
			size = { height = 12 },
		},
		preview = {
			type = "main",
			scratch = true,
		},
		icons = {
			indent = {
				top = "│ ",
				middle = "├╴",
				last = "└╴",
				fold_open = " ",
				fold_closed = " ",
				ws = "  ",
			},
		},
		modes = {
			diagnostics = {
				groups = {
					{ "filename", format = "{file_icon} {basename:Title} {count}" },
				},
				format = "{severity_icon} {message:md} {item.source} ({code}) {pos}",
			},
			symbols = {
				focus = true,
				win = { position = "right", size = { width = 0.3 } },
			},
			lsp = {
				groups = {
					{ "filename", format = "{file_icon} {basename:Title} {count}" },
				},
			},
		},
		keys = {
			["?"] = "help",
			r = "refresh",
			R = "toggle_refresh",
			q = "close",
			o = "jump_close",
			["<esc>"] = "cancel",
			["<cr>"] = "jump",
			["<2-leftmouse>"] = "jump",
			["<c-s>"] = "jump_split",
			["<c-v>"] = "jump_vsplit",
			p = "preview",
			P = "toggle_preview",
			K = "hover",
			zm = "fold_close_all",
			zM = "fold_close_all",
			zr = "fold_open_all",
			zR = "fold_open_all",
			za = "fold_toggle",
			zA = "fold_toggle_recursive",
			j = "next",
			k = "prev",
			gg = "first",
			G = "last",
			["<c-f>"] = "filter",
			s = "toggle_severity",
		},
	},
}
